#!/bin/bash

# ----------------------------------
# Colors
# ----------------------------------
NOCOLOR=        '\033[0m'
RED=            '\033[0;31m'
GREEN=          '\033[0;32m'
ORANGE=         '\033[0;33m'
BLUE=           '\033[0;34m'
PURPLE=         '\033[0;35m'
CYAN=           '\033[0;36m'
LIGHTGRAY=      '\033[0;37m'
DARKGRAY=       '\033[1;30m'
LIGHTRED=       '\033[1;31m'
LIGHTGREEN=     '\033[1;32m'
YELLOW=         '\033[1;33m'
LIGHTBLUE=      '\033[1;34m'
LIGHTPURPLE=    '\033[1;35m'
LIGHTCYAN=      '\033[1;36m'
WHITE=          '\033[1;37m'

# ------------
# pacman
# ------------
echo -e ${GREEN}'################## Update system by pacman... ##################'
    sudo pacman -Syu --noconfirm    || {
        echo -e ${RED}'################# Update system has failed, skip now... ######################'
    }
# ------------
# AUR
# ------------
echo -e ${GREEN}'################### Update system by yay... ####################'
if command -v yay >/dev/null 2>&1; then
	yay -Syu --noconfirm            || {
		echo -e ${RED}'################# yay command is failed, skipping... ###############'
	}
elif command -v paru >/dev/null 2>&1; then
	paru -Syu --noconfirm           || {
		echo -e ${RED}'############### paru command is failed, skipping... ################'
	}
else
	echo -e ${WHITE}'Did you use Chaotic-aur?'
		echo -e ${RED} '################# Update system has failed, skipping... ######################'
fi

# ------------
# flatpak
# ------------
echo -e ${GREEN}'################### Update system by flatpak... ################'
    flatpak update -y               || {
        echo -e ${RED} '############### flatpak command not found, skipping... #################'
    }


clear

# ------------
# clear cache
# ------------
echo -e ${GREEN}'################ Clear cache ######################'
    sudo pacman -Scc --noconfirm    || {
        echo -e ${RED} '################# Skipping... ######################'
    }

if command -v yay >/dev/null 2>&1; then
    yay -Scc --noconfirm            || {
        echo -e ${RED} '################# Skipping... ######################'
    }
elif command -v paru >/dev/null 2>&1; then
    paru -Scc --noconfirm           || {
        echo -e ${RED} '################# Skipping... ######################'
    }
elif command -v flatpak >/dev/null 2>&1; then
    
    flatpak uninstall --unused -y   || {
        echo -e ${RED} '################# Skipping... ######################' 
    }
else
	    echo -e ${RED} '################# Skipping... ######################'
fi

# done stages 2
clear

echo -e ${GREEN}'############# System info... #################'
# system info and asscii image
    fastfetch   ||  unifetch    ||  neofetch    ||  rxfetch
exit 0
